version: "2.1"
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - 8000:8000
    restart: unless-stopped
  dyanmodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - 8001:8001
    links:
      - dynamodb
    depends_on:
      - dynamodb
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    restart: unless-stopped