version: "2.1"
services:
  youtube2notion:
    image: taehoio/youtube2notion
    container_name: youtube2notion
    ports:
      - 5000:5000/tcp
    command:
      - app.py
    tty: true
    restart: unless-stopped
